schemes:
  - WhisperBoard
targets:
  - WhisperBoardKit
  - WhisperBoard
  - ShareExtension
  - Common
  - AudioProcessing
verbose: false
workspace: WhisperBoard.xcworkspace
report_exclude:
  - App/Derived/*
  - Tuist/*
  - build/*
  - Sources/AppKit/Clients/Secrets.swift
  - Derived/*
