schemes:
  - WhisperBoard
targets:
  - WhisperBoardKit
  - WhisperBoard
  - ShareExtension
verbose: true
workspace: WhisperBoard.xcworkspace
report_exclude:
  - App/Derived/*
  - Tuist/*
  - build/*
  - Sources/AppKit/Clients/Secrets.swift
